dist: trusty
sudo: required

language: cpp

env:
- BUILD_TYPE=Release CPP14=OFF EXCEPTIONS=OFF INT128=ON
- BUILD_TYPE=Release CPP14=OFF EXCEPTIONS=ON INT128=OFF
- BUILD_TYPE=Release CPP14=ON EXCEPTIONS=OFF INT128=ON
- BUILD_TYPE=Release CPP14=ON EXCEPTIONS=ON INT128=OFF
- BUILD_TYPE=Debug CPP14=OFF EXCEPTIONS=OFF INT128=ON
- BUILD_TYPE=Debug CPP14=OFF EXCEPTIONS=ON INT128=OFF
- BUILD_TYPE=Debug CPP14=ON EXCEPTIONS=OFF INT128=ON
- BUILD_TYPE=Debug CPP14=ON EXCEPTIONS=ON INT128=OFF

compiler:
- gcc
- clang

matrix:
  exclude:
    - compiler: clang
      env: BUILD_TYPE=Release CPP14=ON EXCEPTIONS=OFF INT128=ON
    - compiler: clang
      env: BUILD_TYPE=Release CPP14=ON EXCEPTIONS=ON INT128=OFF
    - compiler: clang
      env: BUILD_TYPE=Debug CPP14=ON EXCEPTIONS=OFF INT128=ON
    - compiler: clang
      env: BUILD_TYPE=Debug CPP14=ON EXCEPTIONS=ON INT128=OFF


before_script:
    - source .travis-setup.sh

script:
    - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCPP14="${CPP14}" -DEXCEPTIONS="${EXCEPTIONS}" -DINT128="${INT128}"
    - make fp_test fp_benchmark
    - ./fp_test
    - ./fp_benchmark --benchmark_format=csv>result.csv
    - ./src/benchmark/report.py result.csv
    - ls -l fp_benchmark fp_test
