dist: trusty
sudo: required

language: cpp

# NOTE: The COMPILER variable is unused. It simply makes the display on
# travis-ci.org more readable.
matrix:
    include:
        - compiler: gcc
          env: COMPILER=g++ BUILD_TYPE=Release EXCEPTIONS=ON
        - compiler: gcc
          env: COMPILER=g++ BUILD_TYPE=Release EXCEPTIONS=OFF
        - compiler: clang
          env: COMPILER=clang++ BUILD_TYPE=Release  EXCEPTIONS=ON
        - compiler: clang
          env: COMPILER=clang++ BUILD_TYPE=Release  EXCEPTIONS=OFF
        - compiler: gcc
          env: COMPILER=g++ BUILD_TYPE=Debug EXCEPTIONS=ON
        - compiler: clang
          env: COMPILER=clang++ BUILD_TYPE=Debug EXCEPTIONS=ON

before_script:
    - source .travis-setup.sh

script:
    - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DEXCEPTIONS="${EXCEPTIONS}"
    - make fp_test fp_benchmark
    - ./fp_test
    - ./fp_benchmark --benchmark_format=csv>result.csv
    - ./src/benchmark/report.py result.csv
    - ls -l fp_benchmark fp_test
